---
version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: 'daily'
    groups:
      core-security-updates:
        applies-to: security-updates
        patterns:
          - react
        update-types:
          - 'minor'
          - 'patch'
      core:
        applies-to: version-updates
        patterns:
          - react
        update-types:
          - 'major'

      others-security-updates:
        applies-to: security-updates
        patterns:
          - hot-formula-parser
        update-types:
          - 'minor'
          - 'patch'
      others:
        applies-to: version-updates
        patterns:
          - hot-formula-parser
        update-types:
          - 'major'
