---
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      core:
        applies-to: version-updates
        patterns:
          - react
          - body-parser
          - dompurify
          - bootstrap
        update-types:
          - 'major'
      core-security-updates:
        applies-to: security-updates
        patterns:
          - react
          - body-parser
          - dompurify
          - bootstrap
        update-types:
          - 'minor'
          - 'patch'

      others:
        applies-to: version-updates
        patterns:
          - hot-formula-parser
        update-types:
          - 'major'
      others-security-updates:
        applies-to: security-updates
        patterns:
          - hot-formula-parser
        update-types:
          - 'minor'
          - 'patch'
