---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    groups:
      core:
        applies-to: version-updates
        patterns:
          - lodash
          - react
      others:
        applies-to: version-updates
        patterns:
          - hot-formula-parser
          
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    groups:
      core-security-updates:
        applies-to: security-updates
        patterns:
          - lodash
          - react
      others-security-updates:
        applies-to: security-updates
        patterns:
          - hot-formula-parser
