---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    groups:
      core:
        patterns:
          - lodash
      others:
        patterns:
          - hot-formula-parser
