---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    groups:
      core:
        applies-to: version-updates
        patterns:
          - lodash
          - react
        update-types:
          - "major"
      core-security-updates:
        applies-to: security-updates
        patterns:
          - lodash
          - react
        update-types:
          - "patch"
          - "minor"
      others:
        applies-to: version-updates
        patterns:
          - hot-formula-parser
      others-security-updates:
        applies-to: security-updates
        patterns:
          - hot-formula-parser
